folders:
  - {name: "CI-Pipelines", description: "CI Pipeline jobs for All Roboshop Components"}

multibranchJobs:
  - { jobName: "cart", folderName: "CI-Pipelines/", repoName: "cart", componentName: "cart" }
  - { jobName: "catalogue", folderName: "CI-Pipelines/", repoName: "catalogue", componentName: "catalogue" }
  - { jobName: "user", folderName: "CI-Pipelines/", repoName: "user", componentName: "user" }
  - { jobName: "payment", folderName: "CI-Pipelines/", repoName: "payment", componentName: "payment" }
  - { jobName: "shipping", folderName: "CI-Pipelines/", repoName: "shipping", componentName: "shipping" }
  - { jobName: "frontend", folderName: "CI-Pipelines/", repoName: "frontend", componentName: "frontend" }

pipelineJobs:
  - { jobName: "deploy-to-any-env", folderName: "", repoName: "roboshop-jenkins", filename: "Jenkinsfile-any-env-deploy"}
